version: '3.8'
services:
  new-job-challenge-carrefour-api:
    image: img-new-job-challenge-carrefour-api
    container_name: ctn-new-job-challenge-carrefour-api
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres      
    networks:
      - carrefour-api-network        
    depends_on:
    - new-job-challenge-carrefour-db-cache
    - new-job-challenge-carrefour-postgres
    - kafka
    ##- new-job-challenge-carrefour-kafka
    links:
    - new-job-challenge-carrefour-db-cache
    - new-job-challenge-carrefour-postgres
    - kafka
    ##- new-job-challenge-carrefour-kafka    

  new-job-challenge-carrefour-db-cache:
    image: redis:5-alpine
    container_name: ctn-new-job-challenge-carrefour-cache
    restart: always
    volumes:
      - cache:/data  
    ports:
      - 6379:6379
    command: redis-server
    
  new-job-challenge-carrefour-postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: ctn-new-job-challenge-carrefour-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - C:\PostegresDb\data:/data/db
    networks:
      - postgres-compose-network    
            
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper      
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: "9092"
    volumes:
      - c:/docker.sock:/var/run/docker.sock
      
networks:
    postgres-compose-network:
      driver: bridge  
    carrefour-api-network:
      attachable: true   
    kafka-compose-network:
      driver: bridge
volumes:
  cache:
    driver: local